### ISSUE TITLE
object has no attribute 'variation'

### ISSUE THREAD

**Issue by mat214** [kdschmidt1/Sail_Instrument#22]
Greeting,

Thank you for this plugin.

The plugin worked but now it doesn't work anymore and I get the message: "system-Sail_Instrument'Plugin' object has no attribute 'variation'"

How to resolve the problem?

Another question. I use avnav with signalk for data acquisition. The display of the plugins does not seem to work if I do not also send the information in UDP nmea. However, with only the signalk connection, it calculates the derived data well.

**Comment by kdschmidt1** [comment]
hello mat214,
my first impression is that you are using an old version of avnav. could you please try the lates daily [20240405](https://www.wellenvogel.net/software/avnav/downloads/daily/20240405/) or at least the latest release [20230705](https://www.wellenvogel.net/software/avnav/downloads/release/20230705/).
also the second issue with signalk is related to avnav, because the plugin itself does not read any data, instead is only using data from avnav store.
please comment, if this helps, otherwise we have to look further in detail.
regards kd

**Comment by AaskovKnudsen** [comment]
Hello mat214 and kd

I am having exactly the same issue with sailinstrument 20240408.
I am using avnav 20230705 on RPI4
The plugin worked, and suddenly it doesn't work. Restarting avnav server doesn't help immedietly, but suddenly after some minutes, the plugin works again.
Plugin settings are the default.
Please see attached screendump.
regards Jan

![Screenshot_20240425_174442_Samsung Internet](https://github.com/kdschmidt1/Sail_Instrument/assets/150262992/315c26a4-da6a-4fcd-ac9d-ff5e041f0dfc)

**Comment by kdschmidt1** [comment]
hi,
i just checked again and it seems as if the variation has been introduced in avnav only after version 20240405. this could cause the problem. so i ask also you to check with the latest daily (currently [20240422](https://www.wellenvogel.net/software/avnav/downloads/daily/20240422/). unfortunately i have not received any answer from mat214. i will ask andreas when the next release-version is planned, because there have been a lot of modifications in reading and storing of input values. it would be nice to get an answer from you, if it is working with the last version. this would give me the possibility to change the dependencies for the installation.
regards kd

**Comment by mat214** [comment]
Good morning,
Sorry for not responding, I was at sea and then I didn't come back to you.

The variation problem comes from the fact that my gnss returned a null value for magnetic variation. I use the magnetic variation of the signalk derived data plugins, I set signalk to use this value and it works very well.

But if you need to know that avanav does not manage nmea connections I let signalk take care of it.

I have two questions/problems left:

the refresh rate of the data calculation by the plugins is very slow for sending to my instruments. I have to keep derived data to send VMG type data to my network.

I don't understand how to install the polars of my first 25. the .pol files do not look like the polar file of the plugins.

**Comment by kdschmidt1** [comment]
hello mat214,
first quick answer to your questions:
you can change the refresh rate by adjusting the period in the configuration of the plugin ( i.e. to 0.1 sec).
for the polar file i will come back with an explanation soon, but is is simply a 2-dimensional matrix of speed through water with the x-axis as vector TWS and y-axis as vector TWA. you can modify it using the [download page/UserFiles -> Edit](https://www.wellenvogel.net/software/avnav/docs/userdoc/downloadpage.html?lang=en#h3:UserFilesl)
regards kd

**Comment by kdschmidt1** [comment]
hello jan, mat214,
unfortunately i'm not able to reproduce the issue on my development system. Could you please provide a NMEA-Logfile of the data where you observed the failure?
(Procedure: [Server/Status-Page](https://www.wellenvogel.net/software/avnav/docs/userdoc/statuspage.html?lang=en) -> AVNNmeaLogger: Empty filter string and set interval to 0, empty the tracks directory, restart avnav and let it run for some time, provide the created xxxx-xx-xx.nmea file from tracks directory).
thank you and regards
kd

**Comment by kdschmidt1** [comment]
hello jan, mat214,
i think i found the mistake. i made a new [PreRelease (20240427)](https://github.com/kdschmidt1/Sail_Instrument/releases/tag/20240427). It would be nice if you could test it before i ask to publish it in the repositories.
regards kd

**Comment by AaskovKnudsen** [comment]
Hi kd
Glad to hear you probably found the reason.
I would like to test 20240427, but I need some hints how to install it.
My knowledge to debian is not so good.
I normally use the update screen inn avnav, so I am not sure what to do with the "avnav-sailinstrument-plugin_20240427_all.deb" file.
My avnav installation is based on an openplotter image.
Could you give me some hints?
regards Jan

**Comment by kdschmidt1** [comment]
Hi jan,

the precedure is described in the installation section of the wiki.

Simply download the package (https://github.com/kdschmidt1/Sail_Instrument/releases/tag/20240427) and then run

sudo apt install /path/to/avnav-sailinstrument-plugin_xxxx.deb

from the command line in the terminal. (be aware that it might take up to 600 (wmm_period) seconds before the plugin is calculating the actual variation. This will be fixed with the upcoming release).

Regards kd

 

 

Dr.-Ing. Klaus Dieter Schmidt 

Hauptstrasse 52A 

D-78269 Volkertshausen 

***@***.*** 

*+49 171 36 19 275

 

Von: AaskovKnudsen ***@***.***> 
Gesendet: Sonntag, 28. April 2024 08:00
An: kdschmidt1/Sail_Instrument ***@***.***>
Cc: kdschmidt1 ***@***.***>; State change ***@***.***>
Betreff: Re: [kdschmidt1/Sail_Instrument] object has no attribute 'variation' (Issue #22)

 

Hi kd
Glad to hear you probably found the reason.
I would like to test 20240427, but I need some hints how to install it.
My knowledge to debian is not so good.
I normally use the update screen inn avnav, so I am not sure what to do with the "avnav-sailinstrument-plugin_20240427_all.deb" file.
My avnav installation is based on an openplotter image.
Could you give me some hints?
regards Jan

**Comment by kdschmidt1** [comment]
Hi jan,
the precedure is described in the installation section of the wiki.
Simply download the package (https://github.com/kdschmidt1/Sail_Instrument/releases/tag/20240427) and then run
sudo apt install /path/to/avnav-sailinstrument-plugin_xxxx.deb
from the command line in the terminal. (be aware that it might take up to 600 (wmm_period) seconds before the plugin is calculating the actual variation. This will be fixed with the upcoming release).
Regards kd

**Comment by AaskovKnudsen** [comment]
Hi kd
I have now tested 20240427 for some hours without any problem, so I think you solved the issue.
Thank you for helping.
Regards Jan

**Comment by kdschmidt1** [comment]
Hi Jan,Nice, thank you for the reply.regards kdVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: AaskovKnudsen ***@***.***> Datum: 29.04.24  11:28  (GMT+01:00) An: kdschmidt1/Sail_Instrument ***@***.***> Cc: kdschmidt1 ***@***.***>, State change ***@***.***> Betreff: Re: [kdschmidt1/Sail_Instrument] object has no attribute 'variation' (Issue #22) 
Hi kd
I have now tested 20240427 for some hours without any problem, so I think you solved the issue.
Thank you for helping.
Regards Jan
